// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../contracts.generated";

export type FetchOptimizationReportPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.FetchOptimizationReportPayload;
export type FetchOptimizationReportReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.FetchOptimizationReportReply;
export type FetchOptimizationRunsPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.FetchOptimizationRunsPayload;
export type FetchOptimizationRunsReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.FetchOptimizationRunsReply;
export type OptimizationAction = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationAction;
export type OptimizationCompletedEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationCompletedEvent;
export type OptimizationFailedEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationFailedEvent;
export type OptimizationReport = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationReport;
export type OptimizationReportErrorEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationReportErrorEvent;
export type OptimizationReportReadyEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationReportReadyEvent;
export type OptimizationRunSummary = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.OptimizationRunSummary;
export type RunOptimizationPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.RunOptimizationPayload;
export type RunOptimizationReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Optimization.RunOptimizationReply;
