// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../contracts.generated";

export type CancelRunPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.CancelRunPayload;
export type CancelRunReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.CancelRunReply;
export type FetchRunsPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.FetchRunsPayload;
export type FetchRunsReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.FetchRunsReply;
export type RunCancelledEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.RunCancelledEvent;
export type RunSummary = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Runs.RunSummary;
