// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../contracts.generated";

export type ExperimentSummary = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.ExperimentSummary;
export type FetchExperimentsPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.FetchExperimentsPayload;
export type FetchExperimentsReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.FetchExperimentsReply;
export type FetchSimulationReportPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.FetchSimulationReportPayload;
export type FetchSimulationReportReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.FetchSimulationReportReply;
export type RunSimulationPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.RunSimulationPayload;
export type RunSimulationReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.RunSimulationReply;
export type SimulationCompletedEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationCompletedEvent;
export type SimulationFailedEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationFailedEvent;
export type SimulationReportActionSuccess = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportActionSuccess;
export type SimulationReportCapabilityImpact = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportCapabilityImpact;
export type SimulationReportCapabilityStatus = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportCapabilityStatus;
export type SimulationReportCdfPoint = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportCdfPoint;
export type SimulationReportCharts = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportCharts;
export type SimulationReportConvergencePoint = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportConvergencePoint;
export type SimulationReportEdgeTraversal = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportEdgeTraversal;
export type SimulationReportErrorEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportErrorEvent;
export type SimulationReportHistogramBucket = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportHistogramBucket;
export type SimulationReportHostCompromise = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportHostCompromise;
export type SimulationReportReadyEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportReadyEvent;
export type SimulationReportSummary = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Simulation.SimulationReportSummary;
