// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../contracts.generated";

export type DocumentCatalogFilterOptions = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Workspace.DocumentCatalogFilterOptions;
export type DocumentCatalogGraphFilterOption = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Workspace.DocumentCatalogGraphFilterOption;
export type DocumentCatalogItem = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Workspace.DocumentCatalogItem;
export type FetchDocumentCatalogPayload = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Workspace.FetchDocumentCatalogPayload;
export type FetchDocumentCatalogReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Workspace.FetchDocumentCatalogReply;
