// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../contracts.generated";

export type DashboardError = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.DashboardError;
export type ExecutionProgressEvent = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.ExecutionProgressEvent;
export type ReportRequestReply = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.ReportRequestReply;
