// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../contracts.generated";

export type AuthenticatesToEdge = __Contracts.NetworkDefense.Graph.Contracts.AuthenticatesToEdge;
export type ContainsEdge = __Contracts.NetworkDefense.Graph.Contracts.ContainsEdge;
export type CredentialNode = __Contracts.NetworkDefense.Graph.Contracts.CredentialNode;
export type Edge = __Contracts.NetworkDefense.Graph.Contracts.Edge;
export type GraphContract = __Contracts.NetworkDefense.Graph.Contracts.GraphContract;
export type HasVulnerabilityEdge = __Contracts.NetworkDefense.Graph.Contracts.HasVulnerabilityEdge;
export type HostNode = __Contracts.NetworkDefense.Graph.Contracts.HostNode;
export type MissionCapabilityNode = __Contracts.NetworkDefense.Graph.Contracts.MissionCapabilityNode;
export type NetworkSegmentNode = __Contracts.NetworkDefense.Graph.Contracts.NetworkSegmentNode;
export type Node = __Contracts.NetworkDefense.Graph.Contracts.Node;
export type NodeViewData = __Contracts.NetworkDefense.Graph.Contracts.NodeViewData;
export type RunsEdge = __Contracts.NetworkDefense.Graph.Contracts.RunsEdge;
export type SaveGraphContract = __Contracts.NetworkDefense.Graph.Contracts.SaveGraphContract;
export type SegmentReachabilityEdge = __Contracts.NetworkDefense.Graph.Contracts.SegmentReachabilityEdge;
export type ServiceNode = __Contracts.NetworkDefense.Graph.Contracts.ServiceNode;
export type StoresCredentialEdge = __Contracts.NetworkDefense.Graph.Contracts.StoresCredentialEdge;
export type SupportsEdge = __Contracts.NetworkDefense.Graph.Contracts.SupportsEdge;
export type VulnerabilityNode = __Contracts.NetworkDefense.Graph.Contracts.VulnerabilityNode;
