// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../contracts.generated";

export type OptimizationParams = __Contracts.NetworkDefense.Optimization.Contracts.OptimizationParams;
export type RunOptimizationRequest = __Contracts.NetworkDefense.Optimization.Contracts.RunOptimizationRequest;
