// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../contracts.generated";

export type RunSimulationRequest = __Contracts.NetworkDefense.Simulation.Contracts.RunSimulationRequest;
export type SimulationParams = __Contracts.NetworkDefense.Simulation.Contracts.SimulationParams;
