defprotocol NetworkDefense.Actions.Action do
  @moduledoc """
  Specifies a protocol for all simulator actions.

  An action is an operation that represents attacker operations during the attack.
  Formally, it performs transistion from state S_n to S_n+1.

  Actions are generated by rules during simulation run.

  Actions whose execution chance is probalistic are first sampled inside simulator and then (if) executed.
  """
  alias NetworkDefense.AttackerState.AttackerState
  @spec execute(t(), AttackerState.t()) :: AttackerState.t()
  def execute(action, simulation_state)

  @spec probability(t()) :: float()
  def probability(action)

  @spec key(t()) :: term()
  def key(action)
end
