// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
// Source: graph inspector contracts

export type FieldKind =
  "string" | "number" | "boolean" | "enum" | "object" | "list" | "unknown";

export interface FieldMetadata {
  name: string;
  kind: FieldKind;
  nullable: boolean;
  choices?: readonly string[];
  contract?: string;
  itemContract?: string;
}

export interface ContractMetadata {
  fields: readonly FieldMetadata[];
}

export const contractMetadata = {
  "NetworkDefense.Graph.Contracts.Data.AuthenticatesToData": {
    fields: [
      {
        name: "granted_privilege",
        kind: "enum",
        nullable: false,
        choices: ["user", "administrator"],
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.ContainsData": {
    fields: [],
  },
  "NetworkDefense.Graph.Contracts.Data.CredentialData": {
    fields: [
      {
        name: "credential_type",
        kind: "enum",
        nullable: false,
        choices: ["password", "ssh_key", "token"],
      },
      {
        name: "identifier",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.CvssData": {
    fields: [
      {
        name: "attack_complexity",
        kind: "enum",
        nullable: false,
        choices: ["low", "high"],
      },
      {
        name: "attack_vector",
        kind: "enum",
        nullable: false,
        choices: ["network", "adjacent", "local", "physical"],
      },
      {
        name: "availability_impact",
        kind: "enum",
        nullable: false,
        choices: ["none", "low", "high"],
      },
      {
        name: "confidentiality_impact",
        kind: "enum",
        nullable: false,
        choices: ["none", "low", "high"],
      },
      {
        name: "integrity_impact",
        kind: "enum",
        nullable: false,
        choices: ["none", "low", "high"],
      },
      {
        name: "privileges_required",
        kind: "enum",
        nullable: false,
        choices: ["none", "low", "high"],
      },
      {
        name: "scope",
        kind: "enum",
        nullable: false,
        choices: ["unchanged", "changed"],
      },
      {
        name: "user_interaction",
        kind: "enum",
        nullable: false,
        choices: ["none", "required"],
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.HasVulnerabilityData": {
    fields: [
      {
        name: "granted_privilege",
        kind: "enum",
        nullable: false,
        choices: ["user", "administrator"],
      },
      {
        name: "required_privilege",
        kind: "enum",
        nullable: false,
        choices: ["none", "user", "administrator"],
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.HostData": {
    fields: [
      {
        name: "name",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.MissionCapabilityData": {
    fields: [
      {
        name: "description",
        kind: "string",
        nullable: true,
      },
      {
        name: "impact_weight",
        kind: "number",
        nullable: false,
      },
      {
        name: "min_operational_support",
        kind: "number",
        nullable: false,
      },
      {
        name: "name",
        kind: "string",
        nullable: false,
      },
      {
        name: "required_flows",
        kind: "list",
        nullable: false,
        itemContract:
          "NetworkDefense.Graph.Contracts.Data.RequiredServiceFlowData",
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.NetworkSegmentData": {
    fields: [
      {
        name: "cidr",
        kind: "string",
        nullable: true,
      },
      {
        name: "name",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.RequiredServiceFlowData": {
    fields: [
      {
        name: "source_segment_id",
        kind: "string",
        nullable: false,
      },
      {
        name: "target_service_id",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.RunsData": {
    fields: [],
  },
  "NetworkDefense.Graph.Contracts.Data.SegmentReachabilityData": {
    fields: [
      {
        name: "port_end",
        kind: "number",
        nullable: true,
      },
      {
        name: "port_start",
        kind: "number",
        nullable: true,
      },
      {
        name: "protocol",
        kind: "enum",
        nullable: false,
        choices: ["tcp", "udp", "any"],
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.ServiceData": {
    fields: [
      {
        name: "name",
        kind: "string",
        nullable: false,
      },
      {
        name: "port",
        kind: "number",
        nullable: false,
      },
      {
        name: "protocol",
        kind: "enum",
        nullable: false,
        choices: ["tcp", "udp"],
      },
      {
        name: "version",
        kind: "string",
        nullable: true,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.StoresCredentialData": {
    fields: [
      {
        name: "required_privilege",
        kind: "enum",
        nullable: false,
        choices: ["user", "administrator"],
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Data.SupportsData": {
    fields: [],
  },
  "NetworkDefense.Graph.Contracts.Data.VulnerabilityData": {
    fields: [
      {
        name: "cvss",
        kind: "object",
        nullable: false,
        contract: "NetworkDefense.Graph.Contracts.Data.CvssData",
      },
      {
        name: "exploit_probability",
        kind: "number",
        nullable: false,
      },
      {
        name: "identifier",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Edge": {
    fields: [
      {
        name: "data",
        kind: "unknown",
        nullable: false,
      },
      {
        name: "from_id",
        kind: "string",
        nullable: false,
      },
      {
        name: "id",
        kind: "string",
        nullable: false,
      },
      {
        name: "to_id",
        kind: "string",
        nullable: false,
      },
      {
        name: "type",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.GraphContract": {
    fields: [
      {
        name: "edges",
        kind: "list",
        nullable: false,
        itemContract: "NetworkDefense.Graph.Contracts.Edge",
      },
      {
        name: "id",
        kind: "string",
        nullable: false,
      },
      {
        name: "nodes",
        kind: "list",
        nullable: false,
        itemContract: "NetworkDefense.Graph.Contracts.Node",
      },
      {
        name: "parent_revision_id",
        kind: "string",
        nullable: true,
      },
      {
        name: "revision_id",
        kind: "string",
        nullable: true,
      },
      {
        name: "revision_kind",
        kind: "string",
        nullable: true,
      },
      {
        name: "revision_number",
        kind: "number",
        nullable: true,
      },
      {
        name: "title",
        kind: "string",
        nullable: false,
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.Node": {
    fields: [
      {
        name: "data",
        kind: "unknown",
        nullable: false,
      },
      {
        name: "id",
        kind: "string",
        nullable: false,
      },
      {
        name: "type",
        kind: "string",
        nullable: false,
      },
      {
        name: "view_data",
        kind: "object",
        nullable: false,
        contract: "NetworkDefense.Graph.Contracts.NodeViewData",
      },
    ],
  },
  "NetworkDefense.Graph.Contracts.NodeViewData": {
    fields: [
      {
        name: "radius",
        kind: "number",
        nullable: true,
      },
      {
        name: "x_pos",
        kind: "number",
        nullable: false,
      },
      {
        name: "y_pos",
        kind: "number",
        nullable: false,
      },
    ],
  },
} as const satisfies Readonly<Record<string, ContractMetadata>>;

export const nodeDataContracts = {
  Host: "NetworkDefense.Graph.Contracts.Data.HostData",
  Service: "NetworkDefense.Graph.Contracts.Data.ServiceData",
  Vulnerability: "NetworkDefense.Graph.Contracts.Data.VulnerabilityData",
  Credential: "NetworkDefense.Graph.Contracts.Data.CredentialData",
  NetworkSegment: "NetworkDefense.Graph.Contracts.Data.NetworkSegmentData",
  MissionCapability:
    "NetworkDefense.Graph.Contracts.Data.MissionCapabilityData",
} as const;

export const edgeDataContracts = {
  Runs: "NetworkDefense.Graph.Contracts.Data.RunsData",
  SegmentReachability:
    "NetworkDefense.Graph.Contracts.Data.SegmentReachabilityData",
  HasVulnerability: "NetworkDefense.Graph.Contracts.Data.HasVulnerabilityData",
  StoresCredential: "NetworkDefense.Graph.Contracts.Data.StoresCredentialData",
  AuthenticatesTo: "NetworkDefense.Graph.Contracts.Data.AuthenticatesToData",
  Contains: "NetworkDefense.Graph.Contracts.Data.ContainsData",
  Supports: "NetworkDefense.Graph.Contracts.Data.SupportsData",
} as const;
