// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
// Source: all contracts

export interface AuthenticatesToData {
  granted_privilege: "user" | "administrator";
}

export interface CredentialData {
  credential_type: "password" | "ssh_key" | "token";
  identifier: string;
}

export interface CvssData {
  attack_complexity: string;
  attack_vector: string;
  availability_impact: string;
  confidentiality_impact: string;
  integrity_impact: string;
  privileges_required: string;
  scope: string;
  user_interaction: string;
}

export interface HasVulnerabilityData {
  granted_privilege: "user" | "administrator";
  required_privilege: "none" | "user" | "administrator";
}

export interface HostData {
  name: string;
}

export interface NetworkReachabilityData {
  port_end?: number | null;
  port_start?: number | null;
  protocol: "tcp" | "udp" | "any";
}

export type RunsData = Record<never, never>;

export interface ServiceData {
  name: string;
  port: number;
  protocol: "tcp" | "udp";
  version?: string | null;
}

export interface StoresCredentialData {
  required_privilege: "user" | "administrator";
}

export interface VulnerabilityData {
  cvss: CvssData;
  exploit_probability: number;
  identifier: string;
}

export type Edge =
  | RunsEdge
  | NetworkReachabilityEdge
  | HasVulnerabilityEdge
  | StoresCredentialEdge
  | AuthenticatesToEdge;

export interface RunsEdge {
  type: "Runs";
  data: RunsData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface NetworkReachabilityEdge {
  type: "NetworkReachability";
  data: NetworkReachabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface HasVulnerabilityEdge {
  type: "HasVulnerability";
  data: HasVulnerabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface StoresCredentialEdge {
  type: "StoresCredential";
  data: StoresCredentialData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface AuthenticatesToEdge {
  type: "AuthenticatesTo";
  data: AuthenticatesToData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface GraphContract {
  edges: Edge[];
  id: string;
  nodes: Node[];
  parent_revision_id?: string | null;
  revision_id?: string | null;
  revision_kind?: string | null;
  revision_number?: number | null;
  title: string;
}

export type Node = HostNode | ServiceNode | VulnerabilityNode | CredentialNode;

export interface HostNode {
  type: "Host";
  data: HostData;
  id: string;
  view_data: NodeViewData;
}

export interface ServiceNode {
  type: "Service";
  data: ServiceData;
  id: string;
  view_data: NodeViewData;
}

export interface VulnerabilityNode {
  type: "Vulnerability";
  data: VulnerabilityData;
  id: string;
  view_data: NodeViewData;
}

export interface CredentialNode {
  type: "Credential";
  data: CredentialData;
  id: string;
  view_data: NodeViewData;
}

export interface NodeViewData {
  radius?: number | null;
  x_pos: number;
  y_pos: number;
}

export interface SaveGraphContract {
  edges: Edge[];
  id: string;
  nodes: Node[];
  revision_id: string;
  title: string;
}

export interface OptimizationParams {
  budget: number;
  simulation_params?: SimulationParams | null;
  strategy:
    | "cvss"
    | "simulation_informed"
    | "topology_segmentation"
    | "simulated_annealing";
}

export interface RunOptimizationRequest {
  correlation_id: string;
  graph_revision_id: string;
  optimization_params: OptimizationParams;
}

export interface RunSimulationRequest {
  correlation_id: string;
  graph_revision_id: string;
  simulation_params: SimulationParams;
}

export interface SimulationParams {
  generate_seed: boolean;
  initial_foothold_node_id: string;
  iterations_per_run: number;
  max_attempts: number;
  monte_carlo_trials: number;
  seed: number;
}

export interface CompareGraphsPayload {
  base_revision_id: string;
  comparison_revision_id: string;
}

export interface CompareGraphsReply {
  result?: GraphDiffResult | null;
  status: "ok" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface CreateConnectionDraftPayload {
  new_node_type?: string | null;
  relationship_type:
    | "Runs"
    | "NetworkReachability"
    | "HasVulnerability"
    | "StoresCredential"
    | "AuthenticatesTo";
  source_id: string;
  source_is_from: boolean;
  source_type: "Host" | "Service" | "Vulnerability" | "Credential";
  target_id?: string | null;
  target_type?: string | null;
  x_pos?: number | null;
  y_pos?: number | null;
}

export interface CreateConnectionDraftReply {
  edge?: Edge | null;
  node?: Node | null;
  status: "ok" | "invalid";
}

export interface CreateNodeDraftPayload {
  node_type: "Host" | "Service" | "Vulnerability" | "Credential";
  x_pos: number;
  y_pos: number;
}

export interface CreateNodeDraftReply {
  node?: Node | null;
  status: "ok" | "invalid";
}

export interface ExperimentSummary {
  graph_id: string;
  graph_revision_id: string;
  graph_title: string;
  id: string;
  iteration_count: number;
  run_count: number;
  runtime_ms: number;
  seed: number;
  started_at: string;
}

export interface FetchExperimentsPayload {
  graph_revision_ids: string[];
}

export interface FetchExperimentsReply {
  experiments: ExperimentSummary[];
}

export interface FetchSimulationReportPayload {
  experiment_id: string;
  graph_revision_id: string;
}

export interface FetchSimulationReportReply {
  charts: SimulationReportCharts;
  experiment_id: string;
  graph: GraphContract;
  graph_id: string;
  graph_revision_id: string;
  graph_title: string;
  iteration_count: number;
  run_count: number;
  summary: SimulationReportSummary;
  total_runtime_ms: number;
}

export interface GraphConnectivityReply {
  rules: GraphConnectivityRule[];
}

export interface GraphConnectivityRule {
  from_type: "Host" | "Service" | "Vulnerability" | "Credential";
  relationship_type:
    | "Runs"
    | "NetworkReachability"
    | "HasVulnerability"
    | "StoresCredential"
    | "AuthenticatesTo";
  to_type: "Host" | "Service" | "Vulnerability" | "Credential";
}

export interface GraphDiffCounts {
  added: number;
  removed: number;
  unchanged: number;
}

export interface GraphDiffResult {
  edge_counts: GraphDiffCounts;
  edge_status: GraphDiffStatusEntry[];
  graph: GraphContract;
  node_counts: GraphDiffCounts;
  node_status: GraphDiffStatusEntry[];
}

export interface GraphDiffStatusEntry {
  id: string;
  status: "added" | "removed" | "unchanged";
}

export interface GraphSummary {
  edge_count: number;
  graph_id: string;
  is_favorite: boolean;
  node_count: number;
  parent_revision_id?: string | null;
  revision_id: string;
  revision_kind: string;
  revision_number: number;
  title: string;
}

export interface OpenGraphPayload {
  graph_revision_id: string;
}

export interface OpenGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface OptimizationAction {
  cost: number;
  cvss_score?: number | null;
  id: string;
  kind: string;
  label: string;
}

export interface OptimizationCompletedEvent {
  correlation_id: string;
  graph_id: string;
  graph_revision_id: string;
  report: OptimizationReport;
}

export interface OptimizationFailedEvent {
  correlation_id: string;
  graph_id: string;
  graph_revision_id: string;
  reason: string;
}

export interface OptimizationProgressEvent {
  completed_steps: number;
  correlation_id: string;
  graph_id: string;
  graph_revision_id: string;
  phase: string;
  total_steps: number;
}

export interface OptimizationReport {
  actions: OptimizationAction[];
  requested_budget: number;
  runtime_ms: number;
  strategy:
    | "cvss"
    | "simulation_informed"
    | "topology_segmentation"
    | "simulated_annealing";
  used_budget: number;
}

export interface RunOptimizationPayload {
  request: RunOptimizationRequest;
}

export interface RunOptimizationReply {
  correlation_id: string;
  graph_revision_id: string;
  reason?: string | null;
  status: "accepted" | "rejected";
}

export interface RunSimulationPayload {
  request: RunSimulationRequest;
}

export interface RunSimulationReply {
  correlation_id: string;
  graph_revision_id: string;
  reason?: string | null;
  status: "accepted" | "rejected";
}

export interface SaveGraphPayload {
  graph: SaveGraphContract;
}

export interface SaveGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface SetGraphRevisionFavoritePayload {
  favorite: boolean;
  graph_revision_id: string;
}

export interface SetGraphRevisionFavoriteReply {
  favorite: boolean;
  status: "ok" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface SimulationCompletedEvent {
  correlation_id: string;
  experiment_id: string;
  graph_id: string;
  graph_revision_id: string;
}

export interface SimulationFailedEvent {
  correlation_id: string;
  graph_id: string;
  graph_revision_id: string;
  reason: string;
}

export interface SimulationProgressEvent {
  completed_runs: number;
  correlation_id: string;
  graph_id: string;
  graph_revision_id: string;
  total_runs: number;
}

export interface SimulationReportActionSuccess {
  action_type: string;
  attempts: number;
  successes: number;
}

export interface SimulationReportCdfPoint {
  compromised_hosts: number;
  cumulative_probability: number;
}

export interface SimulationReportCharts {
  action_success: SimulationReportActionSuccess[];
  cdf: SimulationReportCdfPoint[];
  convergence: SimulationReportConvergencePoint[];
  edge_traversal: SimulationReportEdgeTraversal[];
  histogram: SimulationReportHistogramBucket[];
  host_compromise: SimulationReportHostCompromise[];
}

export interface SimulationReportConvergencePoint {
  mean_blast_radius: number;
  run: number;
}

export interface SimulationReportEdgeTraversal {
  edge_id: string;
  traversal_probability: number;
}

export interface SimulationReportErrorEvent {
  experiment_id: string;
  graph_revision_id: string;
  reason: string;
}

export interface SimulationReportHistogramBucket {
  count: number;
  lower_bound: number;
  upper_bound: number;
}

export interface SimulationReportHostCompromise {
  compromise_probability: number;
  host_id: string;
}

export interface SimulationReportSummary {
  blast_radius_p95: number;
  blast_radius_p99: number;
  blast_radius_variance: number;
  expected_blast_radius: number;
  host_count: number;
  max_blast_radius: number;
  median_blast_radius: number;
  min_blast_radius: number;
}
