// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
// Source: all contracts

export type HasVulnerabilityData = Record<never, never>;

export interface HostData {
  name: string;
}

export type NetworkReachabilityData = Record<never, never>;

export type RunsData = Record<never, never>;

export interface ServiceData {
  name: string;
  port: number;
  protocol: "tcp" | "udp";
  version?: string | null;
}

export interface VulnerabilityData {
  cvss_score: number;
  exploit_probability: number;
  identifier: string;
}

export type Edge = RunsEdge | NetworkReachabilityEdge | HasVulnerabilityEdge;

export interface RunsEdge {
  type: "Runs";
  data: RunsData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface NetworkReachabilityEdge {
  type: "NetworkReachability";
  data: NetworkReachabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface HasVulnerabilityEdge {
  type: "HasVulnerability";
  data: HasVulnerabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface GraphContract {
  edges: Edge[];
  id: string;
  lock_version: number;
  nodes: Node[];
  title: string;
}

export type Node = HostNode | ServiceNode | VulnerabilityNode;

export interface HostNode {
  type: "Host";
  data: HostData;
  id: string;
  view_data: NodeViewData;
}

export interface ServiceNode {
  type: "Service";
  data: ServiceData;
  id: string;
  view_data: NodeViewData;
}

export interface VulnerabilityNode {
  type: "Vulnerability";
  data: VulnerabilityData;
  id: string;
  view_data: NodeViewData;
}

export interface NodeViewData {
  radius?: number | null;
  x_pos: number;
  y_pos: number;
}

export interface RunSimulationRequest {
  correlation_id: string;
  graph_id: string;
  simulation_params: SimulationParams;
}

export interface SimulationParams {
  iterations_per_run: number;
  monte_carlo_trials: number;
}

export interface ChartSpec {
  aria_label: string;
  id: string;
  option: unknown;
  takeaway: string;
  title: string;
}

export interface ExperimentSummary {
  graph_id: string;
  graph_title: string;
  id: string;
  iteration_count: number;
  run_count: number;
  runtime_ms: number;
  seed: number;
  started_at: string;
}

export interface FetchExperimentsPayload {
  graph_ids: string[];
}

export interface FetchExperimentsReply {
  experiments: ExperimentSummary[];
}

export interface FetchSimulationReportPayload {
  experiment_id: string;
  graph_id: string;
}

export interface FetchSimulationReportReply {
  charts: ReportCharts;
  experiment_id: string;
  graph_id: string;
  graph_title: string;
  graph_version_at_sim: number;
  iteration_count: number;
  kpis: KpiMetric[];
  run_count: number;
  total_runtime_ms: number;
}

export interface KpiMetric {
  detail: string;
  label: string;
  tone: string;
  value: string;
}

export interface OpenGraphPayload {
  graph_id: string;
}

export interface OpenGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface OptimizeDefensePayload {
  graph_id: string;
}

export interface ReportCharts {
  action_stats: ChartSpec[];
  blast_radius_distribution: ChartSpec[];
  convergence: ChartSpec[];
}

export interface RunSimulationPayload {
  request: RunSimulationRequest;
}

export interface RunSimulationReply {
  correlation_id: string;
  graph_id: string;
  reason?: string | null;
  status: "accepted" | "rejected";
}

export interface SaveGraphPayload {
  graph: GraphContract;
}

export interface SaveGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface SimulationCompletedEvent {
  correlation_id: string;
  experiment_id: string;
  graph_id: string;
}

export interface SimulationFailedEvent {
  correlation_id: string;
  graph_id: string;
  reason: string;
}
