import Config

# Use polling for file change detection inside Docker
# (inotify doesn't propagate across bind mounts on all platforms)
config :file_system, backend: FileSystem.Backends.Poll

if File.exists?(".env") do
  ".env"
  |> File.read!()
  |> String.split("\n")
  |> Enum.each(fn line ->
    if String.contains?(line, "=") and not String.starts_with?(line, "#") do
      [k, v] = String.split(line, "=", parts: 2)
      System.put_env(String.trim(k), String.trim(v))
    end
  end)
end

config :live_svelte, ssr_module: LiveSvelte.SSR.ViteJS, vite_host: "http://localhost:5173"

# Keep traces responsive while debugging without changing production batching.
config :opentelemetry, bsp_scheduled_delay_ms: 250

# Configure your database
config :network_defense, NetworkDefense.Repo,
  username: System.get_env("REPO_USERNAME") || System.get_env("POSTGRES_USER") || "postgres",
  password: System.get_env("REPO_PASSWORD") || System.get_env("POSTGRES_PASSWORD") || "postgres",
  hostname: System.get_env("REPO_HOSTNAME") || "localhost",
  port: String.to_integer(System.get_env("REPO_PORT") || "5433"),
  database:
    System.get_env("REPO_DATABASE") || System.get_env("POSTGRES_DB") || "network_defense_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :network_defense, NetworkDefenseWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip:
      System.get_env("PHX_IP", "127.0.0.1")
      |> String.split(".")
      |> Enum.map(&String.to_integer/1)
      |> List.to_tuple(),
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  watchers: [vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]}],
  static_url: [host: "localhost", port: 5173]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :network_defense, NetworkDefenseWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/gettext/.*(po)$",
      ~r"lib/network_defense_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :network_defense, dev_routes: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
