import Config
config :live_svelte, ssr_module: LiveSvelte.SSR.NodeJS, ssr: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :network_defense, NetworkDefenseWeb.Endpoint, []

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
