// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../../contracts.generated";

export type Anchor = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Anchor;
export type Attachment = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Attachment;
export type FlowGroup = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.FlowGroup;
export type Host = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Host;
export type Issue = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Issue;
export type PolicyGroup = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.PolicyGroup;
export type Segment = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Segment;
export type Service = __Contracts.NetworkDefenseWeb.Contracts.Dashboard.Graph.TopologyProjection.Service;
