// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
// Source: lib/network_defense_web/live/web/dashboard/contracts/

export type HasVulnerabilityData = Record<never, never>;

export interface HostData {
  name: string;
}

export type NetworkReachabilityData = Record<never, never>;

export type RunsData = Record<never, never>;

export interface ServiceData {
  name: string;
  port: number;
  protocol: "tcp" | "udp";
  version?: string | null;
}

export interface VulnerabilityData {
  cvss_score: number;
  exploit_probability: number;
  identifier: string;
}

export type Edge = RunsEdge | NetworkReachabilityEdge | HasVulnerabilityEdge;

export interface RunsEdge {
  type: "Runs";
  data: RunsData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface NetworkReachabilityEdge {
  type: "NetworkReachability";
  data: NetworkReachabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface HasVulnerabilityEdge {
  type: "HasVulnerability";
  data: HasVulnerabilityData;
  from_id: string;
  id: string;
  to_id: string;
}

export interface GraphContract {
  edges: Edge[];
  id: string;
  lock_version: number;
  nodes: Node[];
  title: string;
}

export type Node = HostNode | ServiceNode | VulnerabilityNode;

export interface HostNode {
  type: "Host";
  data: HostData;
  id: string;
  view_data: NodeViewData;
}

export interface ServiceNode {
  type: "Service";
  data: ServiceData;
  id: string;
  view_data: NodeViewData;
}

export interface VulnerabilityNode {
  type: "Vulnerability";
  data: VulnerabilityData;
  id: string;
  view_data: NodeViewData;
}

export interface NodeViewData {
  radius?: number | null;
  x_pos: number;
  y_pos: number;
}

export interface OpenGraphPayload {
  graph_id: string;
}

export interface OpenGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}

export interface SaveGraphPayload {
  graph: GraphContract;
}

export interface SaveGraphReply {
  graph?: GraphContract | null;
  status: "ok" | "stale" | "not_found" | "invalid_graph" | "unmapped_error";
}
