import type {
  Node,
  Edge,
  GraphContract,
  OpenGraphPayload,
  OpenGraphReply,
  SaveGraphPayload,
  SaveGraphReply,
  RunSimulationRequest,
  RunSimulationPayload,
  RunSimulationReply,
  OptimizationAction,
  OptimizationParams as GeneratedOptimizationParams,
  OptimizationReport,
  OptimizationCompletedEvent,
  OptimizationProgressEvent,
  RunOptimizationPayload,
  RunOptimizationReply,
  SimulationParams as GeneratedSimulationParams,
  FetchSimulationReportPayload,
  FetchSimulationReportReply,
  SimulationCompletedEvent,
  SimulationFailedEvent,
  SimulationProgressEvent,
  OptimizationFailedEvent,
  ExperimentSummary,
  FetchExperimentsPayload,
  FetchExperimentsReply,
  CreateNodeDraftPayload,
  CreateNodeDraftReply,
  CreateConnectionDraftPayload,
  CreateConnectionDraftReply,
  GraphConnectivityReply,
  GraphConnectivityRule,
} from "../contracts.generated";

export type {
  HostData,
  ServiceData,
  VulnerabilityData,
  RunsData,
  NetworkReachabilityData,
  HasVulnerabilityData,
  CredentialData,
  StoresCredentialData,
  AuthenticatesToData,
  CredentialNode,
  NetworkReachabilityEdge,
  HasVulnerabilityEdge,
  StoresCredentialEdge,
  AuthenticatesToEdge,
  NodeViewData,
  Node,
  Edge,
  OpenGraphPayload,
  OpenGraphReply,
  SaveGraphPayload,
  SaveGraphReply,
  RunSimulationRequest,
  RunSimulationPayload,
  RunSimulationReply,
  OptimizationAction,
  OptimizationReport,
  OptimizationCompletedEvent,
  OptimizationProgressEvent,
  OptimizationFailedEvent,
  RunOptimizationPayload,
  RunOptimizationReply,
  FetchSimulationReportPayload,
  FetchSimulationReportReply,
  SimulationCompletedEvent,
  SimulationFailedEvent,
  SimulationProgressEvent,
  ExperimentSummary,
  FetchExperimentsPayload,
  FetchExperimentsReply,
  CreateNodeDraftPayload,
  CreateNodeDraftReply,
  CreateConnectionDraftPayload,
  CreateConnectionDraftReply,
  GraphConnectivityReply,
  GraphConnectivityRule,
  GraphSummary,
  SimulationReportErrorEvent,
} from "../contracts.generated";

export type LoadedGraph = GraphContract;

export type SimulationParams = GeneratedSimulationParams;

export type OptimizationStrategy = GeneratedOptimizationParams["strategy"];

/** Optimization runs own their simulation settings; standalone runs keep theirs. */
export type OptimizationParams = GeneratedOptimizationParams;

export type Selectable = Node | Edge;

export type SimulationReportData = FetchSimulationReportReply;
