import type {
  Node,
  Edge,
  GraphContract,
  OpenGraphPayload,
  OpenGraphReply,
  SaveGraphPayload,
  SaveGraphReply,
  RunSimulationRequest,
  RunSimulationPayload,
  RunSimulationReply,
  OptimizationAction,
  OptimizationParams as GeneratedOptimizationParams,
  OptimizationReport,
  OptimizationCompletedEvent,
  OptimizationProgressEvent,
  RunOptimizationPayload,
  RunOptimizationReply,
  RunWorkflowPayload,
  RunWorkflowReply,
  WorkflowCompletedEvent,
  WorkflowFailedEvent,
  SimulationParams as GeneratedSimulationParams,
  FetchSimulationReportPayload,
  FetchSimulationReportReply,
  SimulationReportReadyEvent,
  SimulationCompletedEvent,
  SimulationFailedEvent,
  SimulationProgressEvent,
  OptimizationFailedEvent,
  ExperimentSummary,
  FetchExperimentsPayload,
  FetchExperimentsReply,
  FetchOptimizationReportPayload,
  FetchOptimizationReportReply,
  OptimizationReportReadyEvent,
  FetchOptimizationRunsPayload,
  FetchOptimizationRunsReply,
  CreateNodeDraftPayload,
  CreateNodeDraftReply,
  CreateConnectionDraftPayload,
  CreateConnectionDraftReply,
  GraphConnectivityReply,
  GraphConnectivityRule,
  CompareGraphsPayload,
  CompareGraphsReply,
  GraphDiffResult,
  GraphDiffCounts,
  GraphDiffStatusEntry,
  SetGraphRevisionFavoritePayload,
  SetGraphRevisionFavoriteReply,
  FolderSummary,
  CreateFolderPayload,
  CreateFolderReply,
  DeleteFolderPayload,
  DeleteFolderReply,
  MoveGraphToFolderPayload,
  MoveGraphToFolderReply,
  FetchGraphProjectionPayload,
  FetchGraphProjectionReply,
  GraphProjectionOperationalFlow,
  FetchDocumentCatalogPayload,
  FetchDocumentCatalogReply,
  DocumentCatalogItem,
  DashboardError,
  ErrorCode,
} from "../contracts.generated";

export type {
  HostData,
  ServiceData,
  VulnerabilityData,
  RunsData,
  SegmentReachabilityData,
  HasVulnerabilityData,
  CredentialData,
  NetworkSegmentData,
  StoresCredentialData,
  AuthenticatesToData,
  CredentialNode,
  NetworkSegmentNode,
  SegmentReachabilityEdge,
  HasVulnerabilityEdge,
  StoresCredentialEdge,
  AuthenticatesToEdge,
  ContainsEdge,
  NodeViewData,
  Node,
  Edge,
  OpenGraphPayload,
  OpenGraphReply,
  SaveGraphPayload,
  SaveGraphReply,
  RunSimulationRequest,
  RunSimulationPayload,
  RunSimulationReply,
  OptimizationAction,
  OptimizationCompletedEvent,
  OptimizationReport,
  OptimizationProgressEvent,
  OptimizationFailedEvent,
  OptimizationReportErrorEvent,
  OptimizationRunSummary,
  RunOptimizationPayload,
  RunOptimizationReply,
  RunWorkflowPayload,
  RunWorkflowReply,
  WorkflowCompletedEvent,
  WorkflowFailedEvent,
  FetchSimulationReportPayload,
  FetchSimulationReportReply,
  SimulationReportReadyEvent,
  SimulationCompletedEvent,
  SimulationFailedEvent,
  SimulationProgressEvent,
  ExperimentSummary,
  FetchExperimentsPayload,
  FetchExperimentsReply,
  FetchOptimizationReportPayload,
  FetchOptimizationReportReply,
  OptimizationReportReadyEvent,
  FetchOptimizationRunsPayload,
  FetchOptimizationRunsReply,
  CreateNodeDraftPayload,
  CreateNodeDraftReply,
  CreateConnectionDraftPayload,
  CreateConnectionDraftReply,
  GraphConnectivityReply,
  GraphConnectivityRule,
  CompareGraphsPayload,
  CompareGraphsReply,
  GraphDiffResult,
  GraphDiffCounts,
  GraphDiffStatusEntry,
  SetGraphRevisionFavoritePayload,
  SetGraphRevisionFavoriteReply,
  FolderSummary,
  CreateFolderPayload,
  CreateFolderReply,
  DeleteFolderPayload,
  DeleteFolderReply,
  MoveGraphToFolderPayload,
  MoveGraphToFolderReply,
  FetchGraphProjectionPayload,
  FetchGraphProjectionReply,
  GraphProjectionOperationalFlow,
  FetchDocumentCatalogPayload,
  FetchDocumentCatalogReply,
  DocumentCatalogItem,
  SimulationReportErrorEvent,
  DashboardError,
  ErrorCode,
} from "../contracts.generated";

export type LoadedGraph = GraphContract;

export type GraphSummary = import("../contracts.generated").GraphSummary;

export type SimulationParams = GeneratedSimulationParams;

export type OptimizationStrategy = GeneratedOptimizationParams["strategy"];

/** Optimization runs own their simulation settings; standalone runs keep theirs. */
export type OptimizationParams = GeneratedOptimizationParams;

export type Selectable = Node | Edge;

export type SimulationReportData = FetchSimulationReportReply;
