// AUTO-GENERATED by mix gen.contracts -- DO NOT EDIT
import type * as __Contracts from "../../contracts.generated";

export type AuthenticatesToData = __Contracts.NetworkDefense.Graph.Contracts.Data.AuthenticatesToData;
export type ContainsData = __Contracts.NetworkDefense.Graph.Contracts.Data.ContainsData;
export type CredentialData = __Contracts.NetworkDefense.Graph.Contracts.Data.CredentialData;
export type CvssData = __Contracts.NetworkDefense.Graph.Contracts.Data.CvssData;
export type HasVulnerabilityData = __Contracts.NetworkDefense.Graph.Contracts.Data.HasVulnerabilityData;
export type HostData = __Contracts.NetworkDefense.Graph.Contracts.Data.HostData;
export type MissionCapabilityData = __Contracts.NetworkDefense.Graph.Contracts.Data.MissionCapabilityData;
export type NetworkSegmentData = __Contracts.NetworkDefense.Graph.Contracts.Data.NetworkSegmentData;
export type RequiredServiceFlowData = __Contracts.NetworkDefense.Graph.Contracts.Data.RequiredServiceFlowData;
export type RunsData = __Contracts.NetworkDefense.Graph.Contracts.Data.RunsData;
export type SegmentReachabilityData = __Contracts.NetworkDefense.Graph.Contracts.Data.SegmentReachabilityData;
export type ServiceData = __Contracts.NetworkDefense.Graph.Contracts.Data.ServiceData;
export type StoresCredentialData = __Contracts.NetworkDefense.Graph.Contracts.Data.StoresCredentialData;
export type SupportsData = __Contracts.NetworkDefense.Graph.Contracts.Data.SupportsData;
export type VulnerabilityData = __Contracts.NetworkDefense.Graph.Contracts.Data.VulnerabilityData;

export { contractMetadata } from "../../contracts.generated.runtime";
export type { ContractMetadata, FieldKind, FieldMetadata } from "../../contracts.generated.runtime";
